import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Toaster} from "react-hot-toast";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Product Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`flex flex-col min-screen min-h-dvh ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className='flex items-center justify-center border-b border-slate-900 py-2.5 px-4 w-full h-14'>
          <div className='w-full max-w-5xl pl-4'>
              <Link href={'/'}>
                  <span>Product Catalog</span>
              </Link>
          </div>
      </header>
      <div className='flex grow justify-center bg-black w-full h-full'>
          <div className='flex w-full max-w-5xl'>
              <nav className='w-70 py-4 pr-2 border-r border-slate-900'>
                  <ul className='flex flex-col gap-2'>
                      <li className='rounded-lg pr-2 hover:bg-slate-900 transition-colors overflow-hidden'>
                          <Link className='block py-2 px-4 w-full h-full' href={'/'}>Strona główna</Link>
                      </li>
                      <li className='rounded-lg pr-2 hover:bg-slate-900 transition-colors overflow-hidden'>
                          <Link className='block py-2 px-4 w-full h-full' href={'/products'}>Produkty</Link>
                      </li>
                      <li className='rounded-lg pr-2 hover:bg-slate-900 transition-colors overflow-hidden'>
                          <Link className='block py-2 px-4 w-full h-full' href={'/categories'}>Kategorie</Link>
                      </li>
                  </ul>
              </nav>
              <main className='flex flex-col gap- grow w-full h-full py-12 px-8 bg-white dark:bg-black sm:items-start'>
                  {children}
              </main>
          </div>
      </div>
      <footer className='w-full flex items-center justify-center border-t border-slate-900 py-2.5 px-4 h-14'>
          <div className='flex max-w-5xl'>
              <span className='text-slate-600'>Product Catalog | © copyright 2025</span>
          </div>
      </footer>
        <Toaster />
      </body>
    </html>
  );
}
